apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app.kubernetes.io/instance: devops-knowledge-share 
    app.kubernetes.io/name: devops-knowledge-share
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/instance: devops-knowledge-share 
    app.kubernetes.io/name: devops-knowledge-share
