apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: engineering-bootcamp
  annotations:
    github.com/project-slug: liatrio/engineering-bootcamp
spec:
  type: documentation
  lifecycle: production
  owner: flywheel-core
