apiVersion: v1
kind: Pod
metadata:
  name: test6-two-containers
  namespace: myapp
  labels:
    app: myapp
spec:
  restartPolicy: OnFailure
  containers:
    - name: test6a
      image: myapp:latest
      imagePullPolicy: Always
      command:
      - sleep
      - "6000"
    - name: test6b
      image: nginx:latest
      imagePullPolicy: Always