apiVersion: v1
kind: Pod
metadata:
  name: test7-two-myapp-containers
  namespace: myapp
  labels:
    app: myapp
spec:
  restartPolicy: OnFailure
  containers:
    - name: test7a
      image: myapp:latest
      imagePullPolicy: Always
      command:
      - sleep
      - "6000"
    - name: test7b
      image: myapp:1.24.0
      imagePullPolicy: Always
      command:
      - sleep
      - "6000"