apiVersion: v1
kind: Pod
metadata:
  name: test1-myapp-img-old
  namespace: myapp
  labels:
    app: myapp
spec:
  restartPolicy: OnFailure
  containers:
    - name: test1
      image: myapp:1.24.0
      imagePullPolicy: Always
      command:
      - sleep
      - "6000"