apiVersion: v1
kind: Pod
metadata:
  name: test5-myapp-img-default-ns
  namespace: default
  labels:
    app: myapp
spec:
  restartPolicy: OnFailure
  containers:
    - name: test5
      image: myapp:latest
      imagePullPolicy: Always
      command:
      - sleep
      - "6000"