apiVersion: v1
kind: Pod
metadata:
  name: test2-myapp-img-latest
  namespace: myapp
  labels:
    app: myapp
spec:
  restartPolicy: OnFailure
  containers:
    - name: test2
      image: myapp:latest
      imagePullPolicy: Always
      command:
      - sleep
      - "6000"