apiVersion: v1
kind: Pod
metadata:
  name: test4-non-busybox-img-default-ns
  namespace: default
  labels:
    app: redis
spec:
  restartPolicy: OnFailure
  containers:
    - name: test4
      image: redis
      imagePullPolicy: Always