apiVersion: v1
kind: Pod
metadata:
  name: test1-busybox-img-old
  namespace: busybox
  labels:
    app: busybox
spec:
  restartPolicy: OnFailure
  containers:
    - name: test1
      image: busybox:1.24.0
      imagePullPolicy: Always
      command:
      - sleep
      - "6000"