apiVersion: v1
kind: Pod
metadata:
  name: test6-two-containers
  namespace: busybox
  labels: 
    app: busybox
spec:
  restartPolicy: OnFailure
  containers:
    - name: test6a
      image: busybox:latest
      imagePullPolicy: Always
      command:
      - sleep
      - "6000"
    - name: test6b
      image: nginx:latest
      imagePullPolicy: Always