apiVersion: v1
kind: Pod
metadata:
  name: test7-two-busybox-containers
  namespace: busybox
  labels: 
    app: busybox
spec:
  restartPolicy: OnFailure
  containers:
    - name: test7a
      image: busybox:latest
      imagePullPolicy: Always
      command:
      - sleep
      - "6000"
    - name: test7b
      image: busybox:1.24.0
      imagePullPolicy: Always
      command:
      - sleep
      - "6000"