apiVersion: v1
kind: Pod
metadata:
  name: test2-busybox-img-latest
  namespace: busybox
  labels: 
    app: busybox
spec:
  restartPolicy: OnFailure
  containers:
    - name: test2
      image: busybox:latest
      imagePullPolicy: Always
      command:
      - sleep
      - "6000"