apiVersion: v1
kind: Pod
metadata:
  name: test3-busybox-img-default-ns
  namespace: default
  labels:
    app: busybox
spec:
  restartPolicy: OnFailure
  containers:
    - name: test5
      image: busybox:latest
      imagePullPolicy: Always
      command:
      - sleep
      - "6000"