apiVersion: v1
kind: Pod
metadata:
  name: test6-non-busybox-img
  namespace: busybox
  labels:
    app: redis
spec:
  restartPolicy: OnFailure
  containers:
    - name: test3
      image: redis
      imagePullPolicy: Always