apiVersion: v1
kind: Service
metadata:
  name: dks-api
spec:
  selector:
    app: dks-api
  ports:
  - name: dks-api
    protocol: TCP
    port: {{ .Values.backend.service.port }} 
    targetPort: {{ .Values.backend.service.port }} 
