apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: namespacequotas.policy.example.com
spec:
  group: policy.example.com
  scope: Namespaced
  names:
    plural: namespacequotas
    singular: namespacequota
    kind: NamespaceQuota
    listKind: NamespaceQuotaList
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                maxReplicas:
                  type: integer

---
apiVersion: policy.example.com/v1
kind: NamespaceQuota
metadata:
  name: replica-quota
  namespace: development
spec:
  maxReplicas: 5

---
apiVersion: policy.example.com/v1
kind: NamespaceQuota
metadata:
  name: replica-quota
  namespace: production
spec:
  maxReplicas: 10

